"""remove full_name from user

Revision ID: 351c89225ecb
Revises: 94461cb40a2c
Create Date: 2025-08-13 21:00:16.305666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351c89225ecb'
down_revision = '94461cb40a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
