"""empty message

Revision ID: 51ef89e9eaad
Revises: 49d9f6ba7063, b7c9d2e1f234
Create Date: 2025-08-15 22:56:20.765411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ef89e9eaad'
down_revision = ('49d9f6ba7063', 'b7c9d2e1f234')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
