"""Add common fields to Contact model

Revision ID: 60d68568f1a0
Revises: 3c1a6f330e2e
Create Date: 2025-08-12 21:12:48.465149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d68568f1a0'
down_revision = '3c1a6f330e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(), nullable=False))
    op.add_column('contacts', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('address', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('city', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('state', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.drop_column('contacts', 'age')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'zip_code')
    op.drop_column('contacts', 'state')
    op.drop_column('contacts', 'city')
    op.drop_column('contacts', 'address')
    op.drop_column('contacts', 'phone_number')
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
