"""Remove full_name from User model

Revision ID: 94461cb40a2c
Revises: e10512012911
Create Date: 2025-08-13 20:41:12.995060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94461cb40a2c'
down_revision = 'e10512012911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
