"""Add more fields to Contact model

Revision ID: e8d3512e374a
Revises: 60d68568f1a0
Create Date: 2025-08-12 21:24:51.341857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d3512e374a'
down_revision = '60d68568f1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('preferred_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('personal_email', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('secondary_phone_number', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('postal_address', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('membership_id', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('organizational_unit', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('region', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('usi_number', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('preferred_contact_method', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('blue_card_number', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('license_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_contacts_personal_email'), 'contacts', ['personal_email'], unique=True)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_personal_email'), table_name='contacts')
    op.drop_column('contacts', 'license_number')
    op.drop_column('contacts', 'blue_card_number')
    op.drop_column('contacts', 'preferred_contact_method')
    op.drop_column('contacts', 'usi_number')
    op.drop_column('contacts', 'region')
    op.drop_column('contacts', 'organizational_unit')
    op.drop_column('contacts', 'membership_id')
    op.drop_column('contacts', 'gender')
    op.drop_column('contacts', 'postal_address')
    op.drop_column('contacts', 'secondary_phone_number')
    op.drop_column('contacts', 'personal_email')
    op.drop_column('contacts', 'preferred_name')
    op.drop_column('contacts', 'middle_name')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
